version: '3.7'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - '80:80'
  # envoy:
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: docker/envoy/Dockerfile
  #   ports:
  #     - "8080:8080"
